/turtlesim:
  ros__parameters:
    background_b: 252
    background_g: 243
    background_r: 130
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

